/**
 * Settle to note — the pure half of "a settled chat joins the vault graph".
 *
 * A conversation that is finished is knowledge in a place the vault cannot
 * see: not in search, not in the graph, with no backlinks from the notes it
 * touched. This module turns one into a real note — frontmatter plus a
 * DISTILLED body — and decides where it goes and whether it may be written at
 * all. The Obsidian half (`obsidian/settle-note.ts`) only reads and writes
 * files.
 *
 * Two rules the shape encodes:
 *
 *  1. **Never a transcript dump.** The body is a summary: what was asked
 *     (capped and trimmed), what came back (the last answer, trimmed), and the
 *     work as links. Tool inputs, tool outputs, thinking and intermediate
 *     turns never reach the page. A markdown mirror of a chat is unreadable
 *     and unsearchable, and it is exactly what "settled chats join the graph"
 *     is NOT asking for.
 *  2. **Settled only.** Live chats stay in the hand-rolled DOM: streaming and
 *     the one-live-surface invariant cannot be expressed in markdown, so a
 *     running or blocked conversation has no note to write yet.
 */
import type { Message } from "./model";
import type { ExoPaths } from "./paths";
import type { Recap } from "./recap";
import { documentNewline, frontmatterBounds, patchFrontmatter } from "./frontmatter-patch";
import { terminalConvoState } from "./convo-state";

/** The frontmatter key that ties a note back to the conversation it mirrors.
 *  This — not the filename — is what makes re-settling an UPDATE: a chat that
 *  was renamed after it was settled still finds its own note. */
export const SETTLE_CONVO_KEY = "exo_convo";

/** The tag every settled chat carries, so the whole set is one vault query. */
export const SETTLE_TAG = "exo/chat";

/** The one line that tells the reader what kind of page this is, before they
 *  spend an evening annotating a body that the next settle will overwrite. */
export const SETTLE_BODY_NOTE =
  "*Regenerated by Exo each time this chat is settled. Frontmatter and tags you add are kept; anything written in the body below is not.*";

/** How much of the conversation reaches the page. Caps, not truncation of a
 *  dump: the point is a note you can read in fifteen seconds. */
const MAX_ASKS = 6;
const ASK_CHARS = 220;
const ANSWER_CHARS = 900;

/** How a settled conversation ended. */
export type SettleOutcome = "settled" | "stopped" | "error";

/** The live facts the gate reads. Same vocabulary as `deriveLane`'s snapshot,
 *  and the same activity blockers as settling a chat onto the sidebar's
 *  Settled shelf (`canSettleThread` in core/thread-lifecycle). */
export interface SettleGate {
  streaming: boolean;
  pendingPerm: boolean;
  pendingAsk: boolean;
  hasMessages: boolean;
}

/**
 * May this conversation be settled to a note? Running and blocked are both
 * refused — a turn in flight has no outcome yet, and a chat waiting on you has
 * an answer that is not written. An empty chat has nothing to distil.
 */
export function canSettle(s: SettleGate): boolean {
  if (s.streaming || s.pendingPerm || s.pendingAsk) return false;
  return s.hasMessages;
}

/**
 * The same gate as seen from a sidebar row, which has a lane instead of the
 * raw live flags. A `lane` at all means running or blocked, and both are
 * refused; a BADGE is not — a chat that stopped or errored has still finished,
 * and its note says so in `outcome`. Kept beside `canSettle` so the two
 * readings of "settled" cannot drift.
 */
export function canSettleRow(r: {
  lane?: "running" | "needs-input";
  messageCount: number;
}): boolean {
  return !r.lane && r.messageCount > 0;
}

/** How a settled conversation ended, in the note's vocabulary. */
export function settleOutcome(s: { stopped: boolean; poisoned: boolean }): SettleOutcome {
  // Derived, not restated. The precedence (a stop outranks an error) is a fact
  // about a conversation, not about notes, and it already lives in
  // `terminalConvoState`. Two copies of it were kept in step by a comment
  // saying "matching terminalConvoState", which is the codebase admitting the
  // duplication and proposing prose as the enforcement.
  const { state } = terminalConvoState(s);
  if (state === "stopped") return "stopped";
  return state === "turn-end" ? "settled" : "error";
}

/** Everything the distiller needs about one conversation. Structural, not
 *  `Convo`: this module never sees the view's types. */
export interface SettleSource {
  id: string;
  title: string;
  /** Provider DISPLAY name ("Claude" / "Codex"), not the id — the note is read
   *  by a person. */
  provider: string;
  model: string;
  /** Slug of the agent the chat was bound to via `/as`, when there was one. */
  agent?: string;
  stopped: boolean;
  poisoned: boolean;
  messages: readonly Message[];
}

/** A note, split the way it is written: keys to merge into the frontmatter,
 *  and the whole body below it. */
export interface SettleNote {
  frontmatter: Record<string, unknown>;
  body: string;
}

const trim = (s: string, max: number): string => {
  const flat = s.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1).trimEnd()}…` : flat;
};

/** Every user turn, trimmed — the "what was asked" spine of the note. */
function asks(messages: readonly Message[]): string[] {
  const out: string[] = [];
  for (const m of messages) {
    if (m.role !== "user") continue;
    const text = trim(m.text ?? "", ASK_CHARS);
    if (text) out.push(text);
  }
  return out;
}

/** The last assistant prose — the outcome. Tool segments are skipped: the work
 *  is reported as links further down, never as its own raw output. */
function lastAnswer(messages: readonly Message[]): string {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role !== "assistant") continue;
    const text = m.segments
      .filter((s) => s.t === "text")
      .map((s) => (s.t === "text" ? s.md : ""))
      .join("\n")
      .trim();
    if (text) return trim(text, ANSWER_CHARS);
  }
  return "";
}

/** A vault path as a wikilink — this is what buys the note its backlinks and
 *  its place in the graph. The `.md` extension is dropped so the link resolves
 *  the way a hand-written one would. */
const link = (path: string): string => `[[${path.replace(/\.md$/i, "")}]]`;

/**
 * Distil one conversation into a note. `recap` is the conversation rollup
 * `core/recap.ts` already builds for the Recap Rail — reused rather than
 * re-derived, so the note and the rail can never disagree about what a chat
 * touched.
 */
export function distillConversation(src: SettleSource, recap: Recap): SettleNote {
  const outcome = settleOutcome(src);
  const written = recap.written.map((w) => w.path);
  const frontmatter: Record<string, unknown> = {
    [SETTLE_CONVO_KEY]: settleStamp(src),
    agent: src.agent ?? null,
    provider: src.provider,
    model: src.model,
    outcome,
    files_touched: written,
    tags: [SETTLE_TAG],
  };

  const questions = asks(src.messages);
  const shown = questions.slice(0, MAX_ASKS);
  const answer = lastAnswer(src.messages);
  // Settling again replaces this body wholesale. The Notice says "Settled to
  // <path>", which reads like a create, so nothing else tells the user that the
  // page they are looking at is regenerated. One line, in the page itself, at
  // the moment they are deciding whether to type into it: cheaper than a
  // warning system and it cannot be dismissed and forgotten.
  const lines: string[] = [`# ${src.title}`, "", SETTLE_BODY_NOTE, ""];

  if (outcome !== "settled") {
    lines.push(
      outcome === "stopped"
        ? "> [!warning] This chat was stopped before it finished."
        : "> [!warning] This chat ended with an error.",
      "",
    );
  }

  if (shown.length) {
    lines.push("## Asked", "");
    for (const q of shown) lines.push(`- ${q}`);
    const rest = questions.length - shown.length;
    if (rest > 0) lines.push(`- _…and ${rest} more turn${rest === 1 ? "" : "s"}._`);
    lines.push("");
  }

  if (answer) lines.push("## Outcome", "", answer, "");

  if (written.length || recap.read.length) {
    lines.push("## Work", "");
    for (const w of recap.written) {
      lines.push(`- Changed ${link(w.path)}${w.count && w.count > 1 ? ` ×${w.count}` : ""}`);
    }
    for (const r of recap.read) lines.push(`- Read ${link(r)}`);
    lines.push("");
  }

  if (recap.skills.length) lines.push(`**Skills:** ${recap.skills.join(", ")}`, "");
  if (recap.web.length) {
    lines.push("## Sources", "");
    for (const w of recap.web) lines.push(w.url ? `- <${w.url}>` : `- ${w.label}`);
    lines.push("");
  }

  return { frontmatter, body: `${lines.join("\n").trimEnd()}\n` };
}

/**
 * WHERE SETTLED CHATS GO — one documented choice, resolved through the path
 * helpers rather than hard-coded: `chats/` directly under Exo's root (the
 * `memoryRoot` setting, `exoPaths().root`), beside `reports/` and `agents/`
 * because it is the same kind of thing — output Exo produced that the vault now
 * owns. It moves with the setting for free, so a vault on `_system/` and a
 * fresh one on `_exo/` both get it in the right place without a second setting.
 */
export function settleFolder(paths: ExoPaths): string {
  return paths.chats;
}

/** Room for the ".md" and for the " 12" a collision may add, inside the
 *  255-byte filename limit every filesystem Obsidian runs on enforces. */
const MAX_NAME_BYTES = 180;

/** Filename-safe title. Three things a title can carry that a filename cannot:
 *
 *  - the characters Obsidian refuses, plus the wikilink brackets, which would
 *    make the note's own name unlinkable;
 *  - a LEADING DOT: Obsidian does not index dot-prefixed files, so the note
 *    would never be a TFile, the writer would take its `create` branch on every
 *    settle, and the second one would fail with "File already exists";
 *  - LENGTH: a manual rename can run past the 255-byte filename limit, and
 *    `vault.create` rejects the path outright. Capped in bytes rather than
 *    characters, and on whole code points, so a title in emoji or CJK is
 *    shortened instead of corrupted.
 */
export function settleFileName(title: string): string {
  const safe = title
    .replace(/[\\/:#^[\]|?*"<>]/g, "")
    .replace(/^[.\s]+/, "")
    .trim();
  return capBytes(safe, MAX_NAME_BYTES).trimEnd() || "Chat";
}

const utf8 = new TextEncoder();

function capBytes(s: string, max: number): string {
  if (utf8.encode(s).length <= max) return s;
  let out = "";
  let used = 0;
  for (const ch of s) {
    const size = utf8.encode(ch).length;
    if (used + size > max) break;
    out += ch;
    used += size;
  }
  return out;
}

/** The path a chat's note wants, before collisions are considered. */
export function settleNotePath(folder: string, title: string): string {
  return `${folder}/${settleFileName(title)}.md`;
}

/**
 * The path to actually write. `taken` is every path in the folder that belongs
 * to a DIFFERENT conversation; two chats named "New chat" must not overwrite
 * each other, so the second one gets a numeric suffix.
 */
export function uniqueSettlePath(folder: string, title: string, taken: readonly string[]): string {
  const base = settleNotePath(folder, title);
  if (!taken.includes(base)) return base;
  const name = settleFileName(title);
  for (let n = 2; ; n++) {
    const candidate = `${folder}/${name} ${n}.md`;
    if (!taken.includes(candidate)) return candidate;
  }
}

/**
 * WHO THIS NOTE BELONGS TO. Not `src.id` on its own: that is a counter value,
 * re-seeded on every reload from the ids that survived (`maxIdSuffix` over the
 * stored conversations), so deleting the highest-numbered chat frees its
 * number and the next new chat mints it again. The note is meant to outlive
 * the chat — that is the whole premise of settling — so a bare id lets a
 * stranger walk into a dead chat's note and replace its body.
 *
 * The second half is the turn that OPENED the conversation, the one thing
 * about it that is both durable and unique in practice: rewind and fork only
 * ever cut from the end or mint a new id, so it survives every edit a chat can
 * receive while it stays the same chat. Clearing a tab to a fresh session
 * (`newSessionInTab`) keeps the id but empties the transcript, and that
 * deliberately reads as a different conversation: a brand-new chat wearing an
 * old number gets its own note instead of overwriting the record of the one
 * before it.
 */
export function settleStamp(src: SettleSource): string {
  return `${src.id}-${fnv1a(opening(src.messages))}`;
}

/** The opening user turn, text and timestamp, or "" when there is none. */
function opening(messages: readonly Message[]): string {
  for (const m of messages) {
    if (m.role === "user") return `${m.at ?? 0}:${m.text ?? ""}`;
  }
  return "";
}

function fnv1a(value: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(36);
}

/**
 * Find the note a conversation was already settled to, by its frontmatter
 * stamp rather than by its filename. Re-settling a chat whose title changed
 * (or whose note the user renamed) must still land on the same page, and the
 * filename cannot promise that.
 */
export function findSettledNote(
  files: readonly { path: string; raw: string }[],
  stamp: string,
): string | null {
  const line = new RegExp(`^${SETTLE_CONVO_KEY}:\\s*"?${escapeRe(stamp)}"?\\s*$`, "m");
  for (const f of files) {
    if (line.test(frontmatterBlock(f.raw))) return f.path;
  }
  return null;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** The raw text between the two `---` fences, or "" when there is none. */
function frontmatterBlock(content: string): string {
  if (!/^---\r?\n/.test(content)) return "";
  const start = content.indexOf("\n") + 1;
  const end = content.slice(start).search(/^---(\r?\n|$)/m);
  return end < 0 ? "" : content.slice(start, start + end);
}

/**
 * The user's tags plus ours, in that order, once each.
 *
 * `tags` is the one key we write that the user also writes. Patching it is a
 * REPLACE — the key patcher swallows the whole indented block under a key it
 * owns — so writing `[exo/chat]` over a note filed under `project/onboarding`
 * silently unfiles it. Keeping the key and dropping the values in it is not
 * keeping the note's frontmatter.
 */
function mergeTags(existing: string, ours: unknown): string[] {
  const mine = Array.isArray(ours) ? ours.filter((t): t is string => typeof t === "string") : [];
  const out = frontmatterTags(existing);
  for (const tag of mine) if (!out.includes(tag)) out.push(tag);
  return out;
}

const unquote = (s: string): string =>
  /^(".*"|'.*')$/.test(s) ? s.slice(1, -1).replace(/''/g, "'") : s;

/** Whatever is under `tags:`, in any of the three shapes a vault writes it:
 *  a block sequence, an inline `[a, b]` flow, or a bare comma-separated scalar. */
function frontmatterTags(content: string): string[] {
  const lines = frontmatterBlock(content).split(/\r?\n/);
  const at = lines.findIndex((l) => /^tags\s*:/.test(l));
  if (at < 0) return [];
  const inline = lines[at].slice(lines[at].indexOf(":") + 1).trim();
  if (inline) {
    return inline
      .replace(/^\[|\]$/g, "")
      .split(",")
      .map((t) => unquote(t.trim()))
      .filter(Boolean);
  }
  const out: string[] = [];
  for (let i = at + 1; i < lines.length; i++) {
    const item = /^\s*-\s*(.*\S)\s*$/.exec(lines[i]);
    if (!item) break;
    out.push(unquote(item[1]));
  }
  return out;
}

/**
 * The file to write. A new note is frontmatter + body; an EXISTING note keeps
 * every frontmatter key we did not write (via `patchFrontmatter`, the same
 * byte-preserving patcher the agent tools use) and has its body replaced.
 *
 * Body replacement, not append: the note is a mirror of the conversation, and
 * a mirror that grows a second copy every time you look at it is a duplicate
 * by another name. Frontmatter is merged rather than replaced because the user
 * may well have filed the note — added a `project`, a `status`, a link — and
 * settling again is not a reason to lose that.
 */
export function renderSettleNote(existing: string | null, note: SettleNote): string {
  if (existing === null) return patchFrontmatter(note.body, note.frontmatter);
  const merged = { ...note.frontmatter, tags: mergeTags(existing, note.frontmatter.tags) };
  const patched = patchFrontmatter(existing, merged);
  // The bounds come from `frontmatter-patch`, which is the only correct reader
  // of that shape here. This used to compute them a third time inline and then
  // hard-code `---\n` for the fence it re-emits, so a note written with CRLF
  // came back with one LF fence in the middle of it.
  const bounds = frontmatterBounds(patched);
  if (!bounds) return patchFrontmatter(note.body, note.frontmatter);
  const nl = documentNewline(patched);
  return `${patched.slice(0, bounds.end)}${nl}---${nl}${note.body}`;
}
